[package]
name = "chatapp"
version = "0.1.0"
edition = "2024"
authors = ["Sayed Anower <sayed.anower.17.2@gmail.com>"]
readme = "README.md"

[profile.release]
opt-level = "z" 
lto = true 
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
fr-rust = { git = "https://github.com/sayed-anower/fr-rust" }